spring:
  application:
    name: api-gw
  cloud:
    gateway:
      server:
        webflux:        # dung cho spring-cloud-starter-gateway
#        webmvc:        # dung cho spring-cloud-starter-gateway-server-webmvc
          routes:
            - id: catalog-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/catalog/**
              filters:
                - RewritePath=/api/v1/catalog/(?<segment>.*), /api/v1/$\{segment}
            - id: customer-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/customer/**
              filters:
                - RewritePath=/api/v1/customer/(?<segment>.*), /api/v1/$\{segment}
            - id: invoice-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/invoice/**
              filters:
                - RewritePath=/api/v1/invoice/(?<segment>.*), /api/v1/$\{segment}
# Rewrite
#    http://localhost:8080/api/v1/catalog/artists
# -> http://localhost:8081/api/v1/artists

#    http://localhost:8080/api/v1/customer/customers
# -> http://localhost:8082/api/v1/customers

#    http://localhost:8080/api/v1/invoice/invoices
# -> http://localhost:8082/api/v1/invoices

# http://localhost:8080/api/v1/catalog/invoices
# -> http://localhost:8081/api/v1/invoices

# https://dvc.org.vn/api/danhmuc
# https://dvc.org.vn/api/congdan/

server:
  port: 8080