spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=chinook_catalog;encrypt=false
    username: sa
    password: 123456-aA
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
# Graceful shutdown
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8081
